# Generated by Django 2.1.5 on 2021-11-19 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Aparato',
            fields=[
                ('id_aparato', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Aparato',
                'verbose_name_plural': 'Aparatos',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('cod_clase', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='Clase_Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('codgo_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.Clase')),
            ],
            options={
                'verbose_name': 'Clase-Socio',
                'verbose_name_plural': 'Clases-Socios',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('dni_entrenador', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('experiencia', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('clase_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.Clase')),
            ],
            options={
                'verbose_name': 'Entrenador',
                'verbose_name_plural': 'Entrenadores',
                'ordering': ['nombre_apellido'],
            },
        ),
        migrations.CreateModel(
            name='Entrenador_actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('activ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.Actividad')),
                ('entrenador_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.Entrenador')),
            ],
            options={
                'verbose_name': 'Entrenador-Actividad',
                'verbose_name_plural': 'Entrenadores-Actividades',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('metros_cuadrados', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('aparato_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.Aparato')),
                ('clase_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.Clase')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['metros_cuadrados'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('dni_socio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=200)),
                ('profesion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('cbu', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['nombre_apellido'],
            },
        ),
        migrations.CreateModel(
            name='Socio_actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('id_activ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.Actividad')),
                ('scio_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.Socio')),
            ],
            options={
                'verbose_name': 'Socio-Actividad',
                'verbose_name_plural': 'Socios-Actividades',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AddField(
            model_name='clase_socio',
            name='dni_soc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.Socio'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='clase_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.Clase'),
        ),
    ]
